### ISSUE TITLE
run container failed

### ISSUE THREAD

**Issue by Christophernt** [chaosblade-io/chaosblade-box-agent#6]
branch v1.0.0
make build
make build_image

kubectl get pods -n chaosblade

NAME                           READY   STATUS             RESTARTS       AGE
chaos-agent-66c8b9f8bc-rblhc   0/1     CrashLoopBackOff   1 (118s ago)   6s

NAME                           READY   STATUS   RESTARTS        AGE
chaos-agent-66c8b9f8bc-rblhc   0/1     Error    2 (2m14s ago)   22s

**Comment by MandssS** [comment]
please use : `kubectl describe pod chaos-agent-66c8b9f8bc-rblhc -n chaosblade`  show the detail error
